// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cap.proto

package cap

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamPacket struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=PeerId,proto3" json:"PeerId,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamPacket) Reset()         { *m = StreamPacket{} }
func (m *StreamPacket) String() string { return proto.CompactTextString(m) }
func (*StreamPacket) ProtoMessage()    {}
func (*StreamPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_20b472bdd64c0623, []int{0}
}

func (m *StreamPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamPacket.Unmarshal(m, b)
}
func (m *StreamPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamPacket.Marshal(b, m, deterministic)
}
func (m *StreamPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamPacket.Merge(m, src)
}
func (m *StreamPacket) XXX_Size() int {
	return xxx_messageInfo_StreamPacket.Size(m)
}
func (m *StreamPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamPacket.DiscardUnknown(m)
}

var xxx_messageInfo_StreamPacket proto.InternalMessageInfo

func (m *StreamPacket) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *StreamPacket) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamPacket)(nil), "cap.StreamPacket")
}

func init() { proto.RegisterFile("cap.proto", fileDescriptor_20b472bdd64c0623) }

var fileDescriptor_20b472bdd64c0623 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4e, 0x2c, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x4e, 0x2c, 0x50, 0x72, 0xe0, 0xe2, 0x09, 0x2e,
	0x29, 0x4a, 0x4d, 0xcc, 0x0d, 0x48, 0x4c, 0xce, 0x4e, 0x2d, 0x11, 0x12, 0xe3, 0x62, 0x0b, 0x48,
	0x4d, 0x2d, 0xf2, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x24, 0xb8,
	0xd8, 0x9d, 0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0x60,
	0x5c, 0x23, 0x67, 0x2e, 0x5e, 0xbf, 0xd4, 0x92, 0xf2, 0xfc, 0xa2, 0x6c, 0x88, 0x41, 0x42, 0x46,
	0x5c, 0x6c, 0x1e, 0x89, 0x79, 0x29, 0x39, 0xa9, 0x42, 0x82, 0x7a, 0x20, 0xdb, 0x90, 0xcd, 0x97,
	0xc2, 0x14, 0xd2, 0x60, 0x34, 0x60, 0x34, 0x62, 0xe7, 0x62, 0x0d, 0x2e, 0xc9, 0x2f, 0x4a, 0x35,
	0xe2, 0xe5, 0xe2, 0x76, 0x2c, 0x28, 0xc8, 0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x4b, 0x62,
	0x03, 0x3b, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x06, 0x09, 0x1a, 0xb7, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NetworkStreamClient is the client API for NetworkStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkStreamClient interface {
	Handle(ctx context.Context, opts ...grpc.CallOption) (NetworkStream_HandleClient, error)
}

type networkStreamClient struct {
	cc *grpc.ClientConn
}

func NewNetworkStreamClient(cc *grpc.ClientConn) NetworkStreamClient {
	return &networkStreamClient{cc}
}

func (c *networkStreamClient) Handle(ctx context.Context, opts ...grpc.CallOption) (NetworkStream_HandleClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NetworkStream_serviceDesc.Streams[0], "/cap.NetworkStream/Handle", opts...)
	if err != nil {
		return nil, err
	}
	x := &networkStreamHandleClient{stream}
	return x, nil
}

type NetworkStream_HandleClient interface {
	Send(*StreamPacket) error
	Recv() (*StreamPacket, error)
	grpc.ClientStream
}

type networkStreamHandleClient struct {
	grpc.ClientStream
}

func (x *networkStreamHandleClient) Send(m *StreamPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *networkStreamHandleClient) Recv() (*StreamPacket, error) {
	m := new(StreamPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NetworkStreamServer is the server API for NetworkStream service.
type NetworkStreamServer interface {
	Handle(NetworkStream_HandleServer) error
}

func RegisterNetworkStreamServer(s *grpc.Server, srv NetworkStreamServer) {
	s.RegisterService(&_NetworkStream_serviceDesc, srv)
}

func _NetworkStream_Handle_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetworkStreamServer).Handle(&networkStreamHandleServer{stream})
}

type NetworkStream_HandleServer interface {
	Send(*StreamPacket) error
	Recv() (*StreamPacket, error)
	grpc.ServerStream
}

type networkStreamHandleServer struct {
	grpc.ServerStream
}

func (x *networkStreamHandleServer) Send(m *StreamPacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *networkStreamHandleServer) Recv() (*StreamPacket, error) {
	m := new(StreamPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _NetworkStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cap.NetworkStream",
	HandlerType: (*NetworkStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Handle",
			Handler:       _NetworkStream_Handle_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cap.proto",
}

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

// StoreServer is the server API for Store service.
type StoreServer interface {
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cap.Store",
	HandlerType: (*StoreServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "cap.proto",
}

// ApplicationClient is the client API for Application service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApplicationClient interface {
}

type applicationClient struct {
	cc *grpc.ClientConn
}

func NewApplicationClient(cc *grpc.ClientConn) ApplicationClient {
	return &applicationClient{cc}
}

// ApplicationServer is the server API for Application service.
type ApplicationServer interface {
}

func RegisterApplicationServer(s *grpc.Server, srv ApplicationServer) {
	s.RegisterService(&_Application_serviceDesc, srv)
}

var _Application_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cap.Application",
	HandlerType: (*ApplicationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "cap.proto",
}
